# Generated by Django 2.0 on 2019-04-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positions',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
