# Generated by Django 2.1 on 2018-09-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=500)),
                ('star', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('cod', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'book_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('star', models.CharField(max_length=10)),
                ('image_path', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'book_home',
                'managed': False,
            },
        ),
    ]
