# Generated by Django 2.1.7 on 2019-05-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('price', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cinemas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=20)),
                ('ellipsis', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=20)),
                ('vision', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'movie_base',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=20)),
                ('ellipsis', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=20)),
                ('vision', models.CharField(blank=True, max_length=10, null=True)),
                ('duration', models.CharField(max_length=3)),
                ('introduction', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie_detail',
                'managed': False,
            },
        ),
    ]
